matrix:
  include:
    - language: python            # this works for Linux but is an error on macOS or Windows
      jobs:
        include:
          - name: "Python 3.8.0 on Xenial Linux"
            python: 3.8           # this works for Linux but is ignored on macOS or Windows
          - name: "Python 3.6.0 on Xenial Linux"
            python: 3.6
          - name: "Python 3.7.4 on macOS"
            os: osx
            osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
            language: shell       # 'language: python' is an error on Travis CI macOS
          - name: "Python 3.8.0 on Windows"
            os: windows           # Windows 10.0.17134 N/A Build 17134
            language: shell       # 'language: python' is an error on Travis CI Windows
            before_install:
              - choco install python --version 3.8.0
              - python -m pip install --upgrade pip
            env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
      install: pip3 install --upgrade pip  # all three OSes agree about 'pip3'
      before_script:
        - cd python
      script:
        - python vcypher_test.py || python3 vcypher_test.py

    - language: java
      jdk:
        - openjdk8
        - openjdk9
      before_script:
        - cd java

    - language: rust
      rust:
        - stable
        - beta
        - nightly
      before_script:
        - cd rust
      script:
        - cargo test
      jobs:
        allow_failures:
          - rust: nightly
        fast_finish: true
