matrix:
  include:
    - language: python
      python:
        - 3.8
      before_script:
        - cd python
      script:
        - python3 vcypher_test.py

    - language: java
      jdk:
        - openjdk9
        - openjdk11
      before_script:
        - cd java

    - language: rust
      rust:
        - stable
        - beta
        - nightly
      before_script:
        - cd rust
      script:
        - cargo test
      jobs:
        allow_failures:
          - rust: nightly
        fast_finish: true
